### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by jarrekk**

### CODE REVIEW

**Comment by datatalking** [comment]
Thank you, what are some tips to engrain the github commands that you would recommend?

It seems like github and CLI are software fossils from days gone by as there is no gui interface... no they use a veritable 1980's screen and have these random text commands memorized?

I have to keep a notebook of things to remember, and even then its a constant challenge to remember where I am via text command vs following what I think would be easer as a gui. How can I get into this "CLI is better mindset" assuming it is better.

Thank you so much for your help.

I'll start working on this github update today.

**Comment by datatalking** [comment]
Oh one other question, leancloud.cn doesn't accept an american phone number for verification?
I had to translate it but that was easy enough with google translate.

Are they expecting a certain number of numbers for a phone number?

**Comment by jarrekk** [comment]
GitHub has a GUI application [here](https://desktop.github.com/), it will be easier for you, but you  should know how git works.
About Leancloud you can use [FireBase](https://firebase.google.com/), they have the same function, but in Jalpc only page view count use Leancould to store count data, first you don't need to care about this.

**Comment by jarrekk** [comment]
Now you should go into this repo's settings panel, in `GitHub Pages` please change follow item to `master branch`
image
then you can find it changes to 
image
click this url you can find your own website.

**Pull request merged**
